In [5]:
import numpy as np

NUMPY INDEXING AND SLICING OF VECTOR

In [6]:
arr =  np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
arr[5]

np.int64(16)

In [8]:
arr[1:5]

array([12, 13, 14, 15])

In [9]:
arr_slice = arr[1::2]
arr_slice

array([12, 14, 16, 18, 20])

NUMPY INDEXING AND SLICING OF MATRIX

In [10]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [19]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [16]:
arr[3]

array([16, 17, 18, 19, 20])

In [17]:
arr[0,4]

np.int64(5)

In [18]:
arr[5,4]

np.int64(30)

In [20]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

BOOLEAN INDEXING

In [22]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [24]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])